### PR TITLE
Remove all kernel settings from script.sh. 

### PR DESCRIPTION
**Pull request by johrstrom**
Use user-define kernels or kernels installed in app_jupyter.

@ZQyou I'd be very interested in this if we can manage it. When I launch - I only have python3. Is there something more we need on the OSC side for this?

### CODE REVIEW

**Comment by johrstrom** [comment]
Well if you want to move towards this scheme - I'm very happy to do that.

**Comment by ZQyou** [comment]
We can discuss this on the coming Friday meeting.

**Comment by ZQyou** [comment]
> I lost all my user defined Julia kernels but also some system defined python kernels. Is this expected?
> 
> before: image
> 
> with this update: image

That is not probably what I want for now. It may be too much changes. We can add back Julia kernel code. 

Users who do not run `installkernel` when adding IJullia (see https://www.osc.edu/resources/available_software/software_list/julia) cannot have a kernel in `.local/share/jupyter/kernels/` to be imported. My plan is to put this responsibility back on users. Users should learn and maintain own kernels. This is also related custom conda environment. The code (https://github.com/OSC/bc_osc_jupyter/blob/master/template/script.sh.erb#L313-L335) seem not working anymore. I will double check.

**Comment by ZQyou** [comment]
Sure. Maybe we can have a message on Jupyter app dashboard to recommend users maintaining own Conda and Julia kernels.

**Comment by ZQyou** [comment]
@johrstrom  Hers is update
1. I have made a script for each Julia version so user can easily run the script to create the corresponding Julia kernel (see https://www.osc.edu/resources/available_software/software_list/julia). The kernel is created using `IJulia.installkernel`
2. The code (https://github.com/OSC/bc_osc_jupyter/blob/master/template/script.sh.erb#L313-L336) to create kernels for user-defined conda environments is not working for conda version > 4.4 because there is no `${CONDA_PREFIX}/bin/activate`. Since Pitzer cluster is deployed (2018 Aug), we have upgraded the python default to `3.6-conda5.2`  (where conda version is 4.5) so many users now can only create kernels manually (https://www.osc.edu/resources/getting_started/howto/howto_use_a_condavirtual_environment_with_jupyter). I think it is safe to remove this code. I can also create a kernel-creation script for python like what I do for Julia

There will be another change, which is how we load cuda module. Originally we load the cuda module in the kernel wrapper via the variable `MODULES`. In my new kernel wrapper (see `/apps/project/ondemand/app_jupyter/2.3.2/bin/osc_kernel_wrapper.sh` on Pitzer), I don't do `module purge` so we can load cuda module in `script.sh`. Eventually I would like to install `jupyter-lmod` so user can load/unload any module including cuda anytime. 

Please comment. I will come up with the announcement soon.

**Comment by johrstrom** [comment]
Thanks. I'm sharing an app with you in test with a small update to the card below.

image

I need to go through setting up new kernels.  I think we need 1 page with all the updates (and/or links to them).

I'll give this a spot check, but if you're happy with where we're at we can move forward. I have other major updates that I'd like to get in not during the December Downtime but before Jan 10 (OSU start date).  I suspect we'll be very busy between Jan 1 and the 10th.

**Comment by johrstrom** [comment]
I confirmed this works for me. I see the expected kernels. I _don't_ see Julia kernels < 1.0, and that's expected. Thanks!

**Comment by ZQyou** [comment]
I cannot see the shared app. I got this message "You are not a registered developer for this portal. Please contact oschelp@osc.edu for more information on how to register."

Here is the draft for Jupyter update:

There will be several kernel chagnes, starting on XXXX:
1. The Julia kernels `Julia 0.5.1` and `Julia 0.6.4` are removed.
2. For Julia >= 1.0, the Jupyter kernels are not automatically installed. Users must manually install Julia kernel for Jupyter: https://www.osc.edu/resources/available_software/software_list/julia#install_julia_kernel.
3. For `python/2.7`, `python/3.5` and `python/3.6`, the Jupyter kernels are not automatically installed. Users must manually install Jupyter kernel: https://www.osc.edu/resources/getting_started/howto/howto_use_a_condavirtual_environment_with_jupyter

Please feel free to make any change and let me know if you need more details.

**Comment by johrstrom** [comment]
Oh, sorry, sharing is only on test.

**Comment by ZQyou** [comment]
@johrstrom  Did you got any chance to review the draft for Jupyter update? Is it ready to go?

**Comment by johrstrom** [comment]
Sorry - I don't follow. This got merged. We're looking to deploy this before next semester. So I'm thinking deploying late December or early Jan.

**Comment by ZQyou** [comment]
It is fine for me but I have another related change regarding cuda module. Should I create another merge request?

**Comment by johrstrom** [comment]
Yes please.

**Pull request merged**
