### PR TITLE
Update Kubernetes image

### PR DESCRIPTION
**Pull request by treydock**
This pulls in some new OS packages that Shameema had me install for some newer versions of modules that will be needed to run those modules, I think mostly RStudio.

### CODE REVIEW

**Comment by treydock** [comment]
Forgot to add that the image has been pre-pulled to all worker nodes in test and production clusters so there won't be a pod delay for first user to use each image on a node.

**Comment by johrstrom** [comment]
I take it this needs to be released soon (today?).

**Comment by treydock** [comment]
This might not be needed depending on if Shameema needs the new OS packages for new RStudio installs.

**Comment by treydock** [comment]
So I had to add a new bug fix to the images where the UID/GID of `slurm` user was incorrect, so the version now in this PR incorporates that bug fix.  I think the incorrect UID/GID would likely just cause issues interacting with SLURM (ie submit job) from within the pod.  That was at least the issue ZQ was having when using this image with Singularity.

Same change was made to https://github.com/OSC/bc_osc_rstudio_server/pull/81

**Comment by johrstrom** [comment]
So is this ready to be pulled in then?

**Comment by treydock** [comment]
Not yet, the image itself is still building (takes a couple hours) and I would like ZQ to verify the bug fix works for him.  Once the image is built and ZQ verifies I would also need to pre-pull the image on worker nodes, but that can just be done before we tag a new release but will likely be done today I hope.

**Comment by treydock** [comment]
ZQ confirmed this latest image solved his problems, and I've pulled this latest image down to all Kubernetes worker nodes.  So I think this and https://github.com/OSC/bc_osc_rstudio_server/pull/81 are ready.

**Comment by johrstrom** [comment]
cool, when do you want it released? ++@ZQyou

**Comment by ZQyou** [comment]
I am not using this image for classroom. It can be released anytime.

**Pull request merged**
