### PR TITLE
[DO NOT MERGE] pitzer version

### PR DESCRIPTION
**Pull request by AriettaZ**
### Three kernels available: 
screen shot 2018-10-17 at 6 11 06 pm

### Temporary alert:
screen shot 2018-10-17 at 6 28 45 pm

### Issue:
Need Pitzer debug node information. The current version is using description from Owens.
```
       **debug** - (*1-40 cores*) For short sessions (= 1 hour) the debug queue
        will have the shortest wait time. This is only accessible during 8AM -
        6PM, Monday - Friday. There are 6 of these nodes on Pitzer.
```

### CODE REVIEW

**Comment by ericfranz** [comment]
Look here: https://www.osc.edu/supercomputing/computing/pitzer/queues_and_reservations Ends up there is Debug-regular and Debug-GPU. I'm not sure how to request Debug-GPU yet. @treydock any comments?

**Comment by ericfranz** [comment]
I'm going to keep this open, tag it, and make an rpm based on it.

**Comment by ericfranz** [comment]
I created a new repo for now: https://github.com/OSC/bc_osc_jupyter_pitzer

**Comment by treydock** [comment]
@ericfranz The debug reservation and gpu debug reservations on Pitzer are purposely omitted at this time.  There is also no debug queue defined.

**Pull request closed without merging**
